# Generated by Django 2.2.6 on 2019-10-24 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verificacao', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verificação',
            name='po',
            field=models.FileField(blank=True, upload_to='POs', verbose_name='Ordem de Compra:'),
        ),
        migrations.AlterField(
            model_name='verificação',
            name='xml',
            field=models.FileField(blank=True, upload_to='XMLs', verbose_name='XML:'),
        ),
    ]
